# Generated by Django 2.2.5 on 2020-05-15 08:55

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggitExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Price')),
                ('kind', models.CharField(choices=[('wood', 'Wood'), ('steel', 'Steel'), ('oil', 'Oil')], max_length=32, verbose_name='Kind')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Taggit Example',
                'verbose_name_plural': 'Taggit Examples',
            },
        ),
    ]
